set(EP_BASE_LOCATION_ARGS
	PREFIX "${EP_PREFIX}"
	INSTALL_DIR "${EP_INSTALL}"
)

set(EP_GIT_ARGS
	GIT_SUBMODULES_RECURSE TRUE
	GIT_SHALLOW TRUE
	GIT_PROGRESS FALSE
	GIT_REMOTE_UPDATE_STRATEGY CHECKOUT
)

set(EP_CMAKE_DEFAULT_GENERATOR
	CMAKE_GENERATOR "${CMAKE_GENERATOR}"
	CMAKE_GENERATOR_PLATFORM "${CMAKE_GENERATOR_PLATFORM}"
	CMAKE_GENERATOR_TOOLSET "${CMAKE_GENERATOR_TOOLSET}"
	CMAKE_GENERATOR_INSTANCE "${CMAKE_GENERATOR_INSTANCE}"
)

set(EP_CMAKE_DEFAULT_CONFIGURE_ARGS
	"-Wno-dev"
	"--install-prefix" "<INSTALL_DIR>"
)
if (NOT "${CMAKE_TOOLCHAIN_FILE}" STREQUAL "")
	list(APPEND EP_CMAKE_DEFAULT_CONFIGURE_ARGS
		"--toolchain" "${CMAKE_TOOLCHAIN_FILE}"
	)
endif ()

set(EP_CMAKE_DEFAULT_CONFIGURE_CACHE_ARGS
	"-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}"
	"-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>"
	"-DCMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT:BOOL=FALSE"
	"-DCMAKE_POLICY_DEFAULT_CMP0054:STRING=NEW"
	"-DCMAKE_POLICY_DEFAULT_CMP0077:STRING=NEW"
	"-DCMAKE_POLICY_DEFAULT_CMP0091:STRING=NEW"
	"-DCMAKE_POLICY_DEFAULT_CMP0097:STRING=NEW"
	"-DCMAKE_POLICY_DEFAULT_CMP0126:STRING=NEW"
	"-DCMAKE_POLICY_DEFAULT_CMP0128:STRING=NEW"
	"-DCMAKE_POLICY_DEFAULT_CMP0135:STRING=NEW"
)
foreach (COMMON_LANGUAGE "C" "CUDA" "CXX")
	list(APPEND EP_CMAKE_DEFAULT_CONFIGURE_CACHE_ARGS
		"-DCMAKE_${COMMON_LANGUAGE}_COMPILER:STRING=${CMAKE_${COMMON_LANGUAGE}_COMPILER}"
		"-DCMAKE_${COMMON_LANGUAGE}_EXTENSIONS:BOOL=${CMAKE_${COMMON_LANGUAGE}_EXTENSIONS}"
		"-DCMAKE_${COMMON_LANGUAGE}_FLAGS_INIT:STRING=${CMAKE_${COMMON_LANGUAGE}_FLAGS_INIT}"
		"-DCMAKE_${COMMON_LANGUAGE}_FLAGS_DEBUG_INIT:STRING=${CMAKE_${COMMON_LANGUAGE}_FLAGS_DEBUG_INIT}"
		"-DCMAKE_${COMMON_LANGUAGE}_FLAGS_RELEASE_INIT:STRING=${CMAKE_${COMMON_LANGUAGE}_FLAGS_RELEASE_INIT}"
		"-DCMAKE_${COMMON_LANGUAGE}_STANDARD:STRING=${CMAKE_${COMMON_LANGUAGE}_STANDARD}"
		"-DCMAKE_${COMMON_LANGUAGE}_STANDARD_REQUIRED:BOOL=${CMAKE_${COMMON_LANGUAGE}_STANDARD_REQUIRED}"
	)
endforeach ()
foreach (BUILD_TYPE "EXE" "MODULE" "SHARED")
	list(APPEND EP_CMAKE_DEFAULT_CONFIGURE_CACHE_ARGS
		"-DCMAKE_${BUILD_TYPE}_LINKER_FLAGS_INIT:STRING=${CMAKE_${BUILD_TYPE}_LINKER_FLAGS_INIT}"
		"-DCMAKE_${BUILD_TYPE}_LINKER_FLAGS_DEBUG_INIT:STRING=${CMAKE_${BUILD_TYPE}_LINKER_FLAGS_DEBUG_INIT}"
		"-DCMAKE_${BUILD_TYPE}_LINKER_FLAGS_RELEASE_INIT:STRING=${CMAKE_${BUILD_TYPE}_LINKER_FLAGS_RELEASE_INIT}"
	)
endforeach ()
if (MSVC AND NOT CMAKE_MSVC_RUNTIME_LIBRARY STREQUAL "")
	list(APPEND EP_CMAKE_DEFAULT_CONFIGURE_CACHE_ARGS
		"-DCMAKE_MSVC_RUNTIME_LIBRARY:STRING=${CMAKE_MSVC_RUNTIME_LIBRARY}"
	)
endif ()

set(EP_NO_BUILD_DEFAULT_ARGS
	BUILD_COMMAND
	TEST_COMMAND
	LOG_DOWNLOAD TRUE
	LOG_UPDATE TRUE
	LOG_PATCH TRUE
	LOG_CONFIGURE TRUE
	LOG_INSTALL TRUE
	LOG_MERGED_STDOUTERR TRUE
	LOG_OUTPUT_ON_FAILURE TRUE
)

set(EP_WITH_BUILD_EXTRA_ARGS
	TEST_COMMAND
	LOG_DOWNLOAD TRUE
	LOG_UPDATE TRUE
	LOG_PATCH TRUE
	LOG_CONFIGURE TRUE
	LOG_BUILD TRUE
	LOG_INSTALL TRUE
	LOG_MERGED_STDOUTERR TRUE
	LOG_OUTPUT_ON_FAILURE TRUE
)
